### PR TITLE
Create pt_BR.arb

### PR DESCRIPTION
**Pull request by igorruckert**
Portuguese (Brazil) translation for WSA PacMan

### CODE REVIEW

**Comment by alesimula** [comment]
Maybe I need to improve this; anyway are you sure "On" / "Off" isn't better here?

image

image

**Comment by igorruckert** [comment]
Can be shorted to Lig. / Desl. if needed.

**Comment by alesimula** [comment]
@igorruckert thanks; BTW I created new trandlation entries, for things I missed previously (those starting with "tmpname_")

**Comment by alesimula** [comment]
@igorruckert added options:

```
"settings_option_generic_system": "System",
"settings_option_generic_disabled": "Disabled",

"theme_mode_dark": "Dark",
"theme_mode_light": "Light",
"theme_mica_full": "Full",
"theme_mica_partial": "Partial",
"theme_icon_adaptive_squircle": "Squircle",
"theme_icon_adaptive_circle": "Circle",
"theme_icon_adaptive_rounded_square": "Rounded Square",

"installer_info_version": "Version: {appVersion}",
"installer_info_version_change": "Version: {appVersionOld} => {appVersionNew}",
"installer_info_package": "Package: {appPackage}",
```

**Pull request merged**
