### PR TITLE
Update `embedded-tools` and Add licenses for redistributed software

### PR DESCRIPTION
**Pull request by s1204IT**
axmldec: v1.2.0
build-tools: 34.0.0
platform-tools: 34.0.4

---

- At least for redistribution of `platform-tools` and `build-tools`, `NOTICE.txt` is also required.
- Recommend specifying the version you are using.
  This is optional and can be deleted.

### CODE REVIEW

**Comment by s1204IT** [comment]
@alesimula 
Please review or merge it.

**Comment by alesimula** [comment]
Hello

For axmldec, I used my forked version: https://github.com/alesimula/axmldec

This would allow you to specify the XML file to decode from within the apk, and also decode binary data from the standard input, which I both use in WSA PacMan

Examples:

`axmldec -o output.xml com.example.app.apk -x res/layout/preference.xml`

^ decoding an xml file inside the archive

`type input.xml | axmldec -o output.xml`

^ decoding from stdin

**Comment by alesimula** [comment]
As for the other binaries and DLLs, could you provide the https://dl.google.com/ URL for the exact build tools and platform tools versions?

**Comment by s1204IT** [comment]
> For axmldec, I used my forked version: https://github.com/alesimula/axmldec

Fixed

> As for the other binaries and DLLs, could you provide the https://dl.google.com/ URL for the exact build tools and platform tools versions?

This is not necessary as it is specified in `source.properties`.

**Comment by s1204IT** [comment]
@alesimula Still have any questions?

**Pull request closed without merging**
